apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.metadata.app }}
  ports:
    - name: {{ .Values.ports.name }}
      protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.spec.containerPort }}
      targetPort: {{ .Values.spec.containerPort }}
